apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: litmus-frontend-ingress
  namespace: litmus
spec:
  rules:
  - host: litmus.frontend.com
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: litmusportal-frontend-service
            port:
              number: 9091
  ingressClassName: nginx-frontend
  tls:
     - hosts:
         - litmus.frontend.com
       secretName: litmus-frontend-tls 
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: litmus-backend-ingress
#   namespace: litmus
# spec:
#   rules:
#   - host: litmus.backend.com
#     http:
#       paths:
#       - path: /backend/(.*)
#         pathType: ImplementationSpecific
#         backend:
#           service:
#               name: litmusportal-server-service
#               port:
#                 number: 9002
#   ingressClassName: nginx-backend
#   tls:
#      - hosts:
#          - litmus.backend.com
#        secretName: litmus-backend-tls 