#  apiVersion: networking.k8s.io/v1beta1
#  kind: Ingress
#  metadata:
#    annotations:
#      #kubernetes.io/ingress.class: nginx
#      #cert-manager.io/cluster-issuer: letsencrypt
#      nginx.ingress.kubernetes.io/rewrite-target: /$1
#    name: litmus-backend-ingress
#    namespace: litmus
#  spec:
  
#   rules:
#   - host: litmus.backend.com
#       http:
#         paths:
#           - backend:
#               serviceName: litmusportal-server-service
#               servicePort: 9002
#             pathType: ImplementationSpecific
#             path: /backend/(.*)
#   ingressClassName: nginx-backend

#    # This section is only required if TLS is to be enabled for the Ingress
#   tls:
#      - hosts:
#          - litmus.backend.com
#        secretName: litmus-backend-tls